@startuml

state kMap : zoom=1
state kInitialOverviewMap : all tiles unknown,\ndraw present tiles
state kFillOverviewMapTiles
state kOverviewMap
state kGlobalMap

[*] --> kMap
kMap --> kInitialOverviewMap : turn

kInitialOverviewMap --> kFillOverviewMapTiles
kFillOverviewMapTiles --> kOverviewMap : all tiles drawn
kFillOverviewMapTiles --> kInitialOverviewMap : turn, zoom < 3
kFillOverviewMapTiles --> kGlobalMap : turn

kOverviewMap --> kGlobalMap : turn
kOverviewMap --> kInitialOverviewMap : turn, zoom < 3
kGlobalMap --> kMap : turn


@enduml
