@startuml

state kMap : zoom=1
state kInitialOverviewMap : all tiles unknown,\ndraw present tiles
state kFillOverviewMapTiles
state kOverviewMap

[*] --> kMap
kMap --> kInitialOverviewMap : turn

kInitialOverviewMap --> kFillOverviewMapTiles
kFillOverviewMapTiles --> kOverviewMap : all tiles drawn
kFillOverviewMapTiles --> kInitialOverviewMap : turn, zoom < 3

kOverviewMap --> kMap : turn, zoom > 3
kOverviewMap --> kInitialOverviewMap : turn, zoom < 3
kOverviewMap --> kInitialOverviewMap : boat close\nto the border

@enduml
