@startuml

state kNode : direction = to_next\nreturn cur
state kOutsideNode
state kInRoute : return cur,\ncur += direction
state kEnd : return std::nullopt

[*] --> kNode
kNode --> kInRoute : cur != next_index
kNode --> kEnd : no next point

kInRoute --> kNode : cur == next_index

@enduml
