@startuml

state kWaitForDollar : Clear line
state kWaitForNewLine
state kParseLine : Produce data

[*] --> kWaitForDollar
kWaitForDollar --> kWaitForNewLine : $
kWaitForNewLine --> kParseLine : Newline
kWaitForNewLine --> kWaitForDollar : $, or\nbuffer full
kParseLine --> kWaitForDollar

@enduml

